### ISSUE TITLE
Mount as network drive?

### ISSUE THREAD

**Issue by anonwins** [ImnLu/RcloneMountGUI#2]
Hi, nice tool, is there some way to make it mount the dir as network drive instead of physical disk? if that's too much to ask for, perhaps a way to pass custom arguments/flags to the rclone? thanks

**Comment by muhammetaliaydin** [comment]
As far as I know 'rclone' only allows mounting as disk. If you know how to do this you can contact me.

**Comment by anonwins** [comment]
"can always force network mode and volume name using **--network-mode --volname** YourVolumeName"

**Comment by anonwins** [comment]
I wanted it into network drive mode so that the caching would work better but it turns out there is no difference in how rclone behaves for either virtual drive or virtual network drive, so I would say there's no need to add the option any more. It won't have meaninful differences.
